image: Visual Studio 2017
cache:
  - node_modules
environment:
  matrix:
    - nodejs_version: 9
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - yarn dist
