image: 
- Ubuntu
- Visual Studio 2017
cache:
  - node_modules
stack: node 8
environment:
  matrix:
    - nodejs_version: 8
  APPVEYOR_YML_DISABLE_PS_LINUX: true
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - yarn release
