version: '3'
services:
  web:
    build: ./web
    ports:
      - "8663:8663"
    links:
      - api
    volumes:
      - ./web/src:/app/src
      - ./web/dist:/app/dist
      - ./health-logs:/app/dist/health-logs
  api:
    build: ./api
    ports:
      - "8662:8662"
    links:
      - aqueduct-remote
    volumes:
      - ./api/data:/app/data
      - ./api/dist:/app/dist
      - ./api/src:/app/src
  aqueduct-remote:
    build: ./aqueduct-remote
    expose:
      # DO NOT CHANGE! Aqueduct remote should not be exposed to the host, only to linked containers
      - "8700"
    environment:
      - ETHEREUM_CHAIN
    links:
      - parity
    volumes:
      - ./aqueduct-remote/dist:/app/dist
      - ./aqueduct-remote/src:/app/src
      - ./health-logs:/health-logs
  parity:
    build: ./parity
    expose:
      # DO NOT CHANGE! JSONRPC should not be exposed to the host, only to linked containers
      - "8545"
    environment:
      - ETHEREUM_CHAIN
      - SYNC_BLOCK
    volumes:
      - ./parity-data:/root/.local/share/io.parity.ethereum/
    entrypoint: /bin/bash
    command: ["/runtime-scripts/start.sh"]
