version: '3'
services:
  aqueduct-server:
    build: .
    ports:
      - "8700:8700"
    environment:
      - ETHEREUM_CHAIN
    volumes:
      - ./sdk/keys:/app/key
    tty: true
    stdin_open: true

